version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306